name: Auto Assign Issues to Projects

on:
  issues:
    types: [labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  ToDiscuss: ToDiscuss 🗣️
        
jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to project
        uses: leonsteinhaeuser/project-beta-automations@v1.1.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          # user: epijim
          organization: pharmaverse
          project_id: 3
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
