name: update universe package.json

on:
  push:
    paths:
      - 'data/packages/**.yaml'
    branches:
      - main  # Set a branch to deploy
      - feature/update-universe-pkg-file # TODO: del - for debug

jobs:
  update-universe:
    runs-on: ubuntu-20.04
    container:
      image: rocker/tidyverse:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: create package.json file
        run: |
          install.packages("yaml")
          install.packages("jsonlite")
          library(yaml)
          library(jsonlite)

          yml_dir <- file.path(Sys.getenv("GITHUB_PATH"), "data/packages")
          yml_files <- list.files(yml_dir)

          all_pkg <- data.frame()
          for (f in yml_files) {
            content <- read_yaml(file.path(yml_dir, f))
            pkg_name <- content$name
            pkg_repo <- content$repo
            if (is.null(content$repo) | is.null(content$name)) {
              print(paste("WARNING - check your conf for this file", f))
            } else {
              pkg_df <- data.frame(package = c(pkg_name),
              url = c(file.path("https://github.com", pkg_repo)))
              all_pkg <- rbind(all_pkg, pkg_df)
            }
          }

          json_data <- prettify(toJSON(all_pkg))
          write(json_data, "updated_packages.json")
        shell: Rscript {0}

      - name: Upload packages artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./updated_packages.json
          retention-days: 5

      - name: checkout universe repo
        uses: actions/checkout@v2
        with:
          repository: pharmaverse/universe
          token: ${{ secrets.PHARMAVERSE_BOT }}
          submodules: true  #
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Download packages aartifact
        uses: actions/download-artifact@v3
        with:
          name: packages
      

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update packages.json
          repository: pharmaverse/universe
          commit_user_name: pharmaverse-bot
          commit_user_email: 113703390+pharmaverse-bot@users.noreply.github.com
          branch: main

# TODO: mv ./updated_packages.json ./packages.json